#!/bin/sh

CPUFREQ_GOVERNOR=ondemand
[ -f /etc/default/cpufreq ] && . /etc/default/cpufreq

self=$0

configure_governor() {
	if ! grep -sq "$1" \
		/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	then
		echo "$self: cpufreq governor unavailable: $1."
		return 1
	fi
	echo "$1" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
}

case "$1" in
	start|restart)
		echo -n "Setting cpufreq governor to $CPUFREQ_GOVERNOR "
		if configure_governor "$CPUFREQ_GOVERNOR"
		then
			echo "done."
		else
			echo "FAILED."
			exit 1
		fi
		;;
	stop)
		;;
	*)
		echo "usage: $0 {start|restart}"
		exit 1
		;;
esac
